// <auto-generated />
using System;
using Another_URL_Shortener.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Another_URL_Shortener.Migrations
{
    [DbContext(typeof(ShortURLDbContext))]
    [Migration("20220408203819_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Another_URL_Shortener.Models.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortedURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShortUrls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f46aec3c-3b6b-4217-82ae-3566c9986416"),
                            CreatedOn = new DateTime(2022, 4, 8, 22, 38, 18, 850, DateTimeKind.Local).AddTicks(5538),
                            IsExpired = false,
                            ModifiedOn = new DateTime(2022, 4, 8, 22, 38, 18, 855, DateTimeKind.Local).AddTicks(6739),
                            ShortedURL = "https://blog.jetbrains.com/12345",
                            URL = "https://blog.jetbrains.com/dotnet/2020/11/25/getting-started-with-entity-framework-core-5/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
